version: '3.8'
services:
  medirekor-frontend:
    image: medirekor-frontend
    tty: true
    build:
      context: ./
      dockerfile: ./dockerfile
    container_name: medirekor-frontend-service
    ports: 
      - "3000:3000"
    volumes:
      - ./:/usr/src/app/